### ISSUE TITLE
ghc-pkg-lib-0.3 doesn't compile

### ISSUE THREAD

**Issue by peti** [JPMoresmau/ghc-pkg-lib#6] opened 2015-06-04 14:35 UTC
~~~~~~~~~
configureFlags: --verbose --prefix=/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-haskell-ghc-pkg-lib-0.3.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/lib/ghc-7.10.1/ghc-pkg-lib-0.3 --ghc-option=-j8 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring ghc-pkg-lib-0.3...
Flags chosen: lib-werror=False
Dependency Cabal >=1.14: using Cabal-1.22.2.0
Dependency base <5: using base-4.8.0.0
Dependency directory -any: using directory-1.2.2.0
Dependency filepath -any: using filepath-1.4.0.0
Dependency ghc -any: using ghc-7.10.1
Dependency ghc-paths >=0.1.0: using ghc-paths-0.1.0.9
Using Cabal-1.22.2.0 compiled by ghc-7.10
Using compiler: ghc-7.10.1
Using install prefix:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3
Binaries installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/bin
Libraries installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/lib/ghc-7.10.1/ghc-pkg-lib-0.3
Private binaries installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/libexec
Data files installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/share/x86_64-linux-ghc-7.10.1/ghc-pkg-lib-0.3
Documentation installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/share/doc/x86_64-linux-ghc-7.10.1/ghc-pkg-lib-0.3
Configuration files installed in:
/nix/store/5817a9izzyar4vmwgb0df4880p8q1ql3-haskell-ghc-pkg-lib-0.3/etc
No alex found
Using ar found on system at:
/nix/store/yxg5zsjxp1l16xk7r23rayyc18fkxynk-binutils-2.23.1/bin/ar
No c2hs found
No cpphs found
Using gcc version 4.8.4 given by user at:
/nix/store/ylj1q31a7x3pvcraxk60dyv9y4wmwcrc-gcc-wrapper-4.8.4/bin/gcc
Using ghc version 7.10.1 found on system at:
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/bin/ghc
Using ghc-pkg version 7.10.1 found on system at:
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.16.0 found on system at:
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/bin/hpc
Using hsc2hs version 0.67 found on system at:
/nix/store/bc84hdk730zcdm1c9s5yf2ahpvm51lzp-ghc-7.10.1/bin/hsc2hs
Using hscolour version 1.22 found on system at:
/nix/store/g6mfdhbmwm0499n88bnzd32y96gmnfn9-hscolour-1.23/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/ylj1q31a7x3pvcraxk60dyv9y4wmwcrc-gcc-wrapper-4.8.4/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.23 found on system at:
/nix/store/yxg5zsjxp1l16xk7r23rayyc18fkxynk-binutils-2.23.1/bin/strip
Using tar found on system at:
/nix/store/blyc5sprbm85ph2fmksyhrqislp9j0im-gnutar-1.28/bin/tar
No uhc found
building
Building ghc-pkg-lib-0.3...
Preprocessing library ghc-pkg-lib-0.3...
[1 of 1] Compiling Language.Haskell.Packages ( src/Language/Haskell/Packages.hs, dist/build/Language/Haskell/Packages.o )

src/Language/Haskell/Packages.hs:170:13:
    Couldn't match type ‘[Char]’
                   with ‘Distribution.ModuleName.ModuleName’
    Expected type: InstalledPackageInfo_
                     Distribution.ModuleName.ModuleName
      Actual type: InstalledPackageInfoString
    In the expression: pkgconf
    In the expression:
      pkgconf {exposedModules = convert e, hiddenModules = convert h}

src/Language/Haskell/Packages.hs:170:47:
    Couldn't match type ‘ExposedModule’ with ‘[Char]’
    Expected type: [String]
      Actual type: [ExposedModule]
    In the first argument of ‘convert’, namely ‘e’
    In the ‘exposedModules’ field of a record

src/Language/Haskell/Packages.hs:171:39:
    Couldn't match type ‘ExposedModule’
                   with ‘Distribution.ModuleName.ModuleName’
    Expected type: [Distribution.ModuleName.ModuleName]
      Actual type: [ExposedModule]
    In the ‘hiddenModules’ field of a record
    In the expression:
      pkgconf {exposedModules = convert e, hiddenModules = convert h}
~~~~

**Comment by JPMoresmau** [comment] 2015-06-04 14:41
1. this is an exact duplicate of https://github.com/JPMoresmau/ghc-pkg-lib/issues/5
2. which means it's solved in the source
3. ghc-pkg-lib is currently NOT maintained anymore

**Closed by JPMoresmau** 2015-06-04 14:41 UTC

**Comment by peti** [comment] 2015-06-04 15:17
It would probably be a good idea to mark the package "deprecated" on https://hackage.haskell.org/package/ghc-pkg-lib/maintain.
